### PR TITLE
Use Neos' RageLib fork & build tweaks/fixes

### PR DESCRIPTION
**Pull request by Korioz**
I didn't tested on linux / macos if everything's fine, only counterpart i see is the `dev_win.bat` who is there to generate gta-toolkit dll's so `ytdtoolio` can find them, altough i don't think that's a big deal issue.

### CODE REVIEW

**Comment by kngrektor** [comment]
Do you think you could include Neos' RageLib as a git submodule instead? iirc I had to vendor RageLib so I could patch some windows specific parts, hopefully this isn't necessary with Neos' fork.

**Comment by Korioz** [comment]
There you are, tell me if that's okay

**Comment by kngrektor** [comment]
Hi I just tried building and realized it depends on DirectXTex. DirectXTex is not xplat and therefore will not work :(, that's why I wrote FuckDX.

**Comment by Korioz** [comment]
DirectXTex is needed for `Helpers/DDSIO.cs` / `Helpers/TextureCompression.cs` / `Helpers/TextureConvert.cs` it's the only things where the lib is used and as i see in `YTDToolio` we doesn't use any of the function proposeds in one of these files so this shouldn't be a problem if it is linked with `RageLib`

**Comment by Korioz** [comment]
Or maybe you're saying that if we let it we can't build RageLib on other platforms than windows and so can't build others projects, if that's the case i will remove it from the solution through the `dev_win.bat`

**Comment by Korioz** [comment]
Tested on Windows and Linux everything's working now 👍 
@kngrektor

**Pull request merged**
